/**
 * Centralized icon mapping for the app.
 * Uses Lucide React icons for all UI elements.
 */

import {
  LayoutDashboard,
  BookOpen,
  BookText,
  FileText,
  MessageSquare,
  BookMarked,
  Keyboard,
  RefreshCw,
  TrendingUp,
  Settings,
  Flame,
  Star,
  Zap,
  Trophy,
  Target,
  Crown,
  Heart,
  Sparkles,
  CheckCircle,
  XCircle,
  ChevronLeft,
  ChevronRight,
  Search,
  Volume2,
  Play,
  Pause,
  Undo2,
  Eraser,
  Eye,
  EyeOff,
  Download,
  Upload,
  Trash2,
  Plus,
  X,
  ArrowLeft,
  Brain,
  Flag,
  PenLine,
  Puzzle,
  BarChart3,
  Hand,
  Flower2,
  PartyPopper,
  // Practice tab icons
  Store,
  UtensilsCrossed,
  TrainFront,
  Users,
  ShoppingBag,
  Home,
  GraduationCap,
  MapPin,
  Languages,
  Headphones,
  Dumbbell,
  ArrowRightLeft,
  Lightbulb,
  BookOpenCheck,
  Layers,
  type LucideIcon,
} from 'lucide-react';
import type { PageId } from './types';

export const PAGE_ICONS: Record<PageId, LucideIcon> = {
  dashboard: LayoutDashboard,
  hiragana: BookOpen,       // あ shown as text alongside
  katakana: BookOpen,       // ア shown as text alongside
  kanji: BookText,
  vocabulary: FileText,
  grammar: FileText,
  practice: MessageSquare,
  reading: BookMarked,
  typing: Keyboard,
  review: RefreshCw,
  progress: TrendingUp,
  settings: Settings,
};

// Japanese character badges for nav items that benefit from cultural context
export const PAGE_JP_CHARS: Partial<Record<PageId, string>> = {
  hiragana: 'あ',
  katakana: 'ア',
  kanji: '漢',
  vocabulary: '語',
  grammar: '文',
};

// Re-export commonly used icons for convenience
export {
  LayoutDashboard,
  BookOpen,
  BookText,
  FileText,
  MessageSquare,
  BookMarked,
  Keyboard,
  RefreshCw,
  TrendingUp,
  Settings,
  Flame,
  Star,
  Zap,
  Trophy,
  Target,
  Crown,
  Heart,
  Sparkles,
  CheckCircle,
  XCircle,
  ChevronLeft,
  ChevronRight,
  Search,
  Volume2,
  Play,
  Pause,
  Undo2,
  Eraser,
  Eye,
  EyeOff,
  Download,
  Upload,
  Trash2,
  Plus,
  X,
  ArrowLeft,
  Brain,
  Flag,
  PenLine,
  Puzzle,
  BarChart3,
  Hand,
  Flower2,
  PartyPopper,
  // Practice tab icons
  Store,
  UtensilsCrossed,
  TrainFront,
  Users,
  ShoppingBag,
  Home,
  GraduationCap,
  MapPin,
  Languages,
  Headphones,
  Dumbbell,
  ArrowRightLeft,
  Lightbulb,
  BookOpenCheck,
  Layers,
};
export type { LucideIcon };
